# Generated by Django 3.1.1 on 2021-10-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='User',
            new_name='user',
        ),
    ]
